services:
  mongodb:
    image: mongo:latest
    container_name: library_db
    ports:
      - "27017:27017"
    volumes:                  # <-- THÊM DÒNG NÀY
      - mongo_data:/data/db   # <-- CHUYỂN DÒNG NÀY XUỐNG ĐÂY

  app:
    build: .
    container_name: library_api
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/librarydb
      - USE_MOCK_DB=false
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data: